---

- name: package
  package:
    name: cronie

- name: package
  package:
    name: python-certbot-apache

- name: package
  package:
    name: python-certbot-nginx

- name: letsencrypt · renew cron
  template:
    src: letsencrypt-renew-cron.j2
    dest: "{{ _letsencrypt_renew_cron_target }}/letsencrypt"
