---

- name: package
  package:
    name: "{{ _letsencrypt_packages | distro(vars) }}"

- name: letsencrypt · renew cron
  template:
    src: letsencrypt-renew-cron.j2
    dest: "{{ _letsencrypt_renew_cron_target }}/letsencrypt"
